spring:
  profiles:
    active: "dev"
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/music_finally?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        stat:
          enabled: true
          db-type: h2
          log-slow-sql: true
          slow-sql-millis: 2000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml


#logging:
#  config: classpath:logback.xml
#  level:
#    root: INFO
#  file:
#    path: ./logs
